### ISSUE TITLE
[AddToken] `ankrETH` on `ethereum`

### ISSUE THREAD

**Issue by openb0x** [cowprotocol/token-lists#118]
### Network

MAINNET

### Token Symbol

ankrETH

### Token Name

Ankr Staked ETH

### Decimals

18

### Address

0xE95A203B1a91a908F9B9CE46459d101078c2c3cb

### Image URL

https://ibb.co/ZTBwXSn

### Reason

Ankr has rebranded all of its aXXXc tokens to ankrXXX. Below information 
https://www.ankr.com/docs/liquid-staking/eth/overview/

**Comment by alfetopito** [comment]
Hello @openb0x , thanks for the submission

Keep in mind you need to provide a link to the image directly rather than a page containing the image.

In your case you should use https://i.ibb.co/Jkvbtqf/ankr-ETH-256x256-logo.png instead and it will work

**Comment by openb0x** [comment]
Hey @alfetopito! If I understood you correctly, then I need to make a second request and use the link you sent?

**Comment by alfetopito** [comment]
> Hey @alfetopito! If I understood you correctly, then I need to make a second request and use the link you sent?

Exactly!
Please create a new issue with the same info and the new image link
