### ISSUE TITLE
[AddToken] `FLEX` on `ETHEREUM`

### ISSUE THREAD

**Issue by web3anondev** [cowprotocol/token-lists#122]
### Network

MAINNET

### Token Symbol

FLEX

### Token Name

Flex Coin

### Decimals

18

### Address

0xFcF8eda095e37A41e002E266DaAD7efC1579bc0A

### Image URL

https://raw.githubusercontent.com/web3anondev/flex/main/flex.png

### Reason

Greetings!

OPNX.com will be launching in coming weeks as the major claims trading place. FLEX is its native token. Please add it so that traders may not be confused. There's almost $400k in locked liquidity across Uniswap pools.

Address: 0xfcf8eda095e37a41e002e266daad7efc1579bc0a
Name: Flex Coin
Symbol: FLEX
Coingecko Link: http://www.coingecko.com/en/coins/flex-coin

Uniswap Pools:

http://etherscan.io/address/0x3f61171b1297f6e512c750c172ba86026ab0e820
http://etherscan.io/address/0xfe5ceab42b1bf0662adf30d95e69e32922f39919
http://etherscan.io/address/0x187a0a3269f33302f070266a00358eef87179526
http://etherscan.io/address/0x932a7b9941499f93ee7b1f9bfb3251a123636877

Thanks!

**Comment by alfetopito** [comment]
Already added via https://github.com/cowprotocol/token-lists/issues/112
