### ISSUE TITLE
OHM on Ethereum

### ISSUE THREAD

**Issue by avsavsavs** [cowprotocol/token-lists#140]
### Network

MAINNET

### Token Symbol

OHM

### Token Name

Olympus DAO Token

### Decimals

18

### Address

0x64aa3364f17a4d01c6f1751fd97c2bd3d7e7f1d5

### Image URL

https://s2.coinmarketcap.com/static/img/coins/64x64/9067.png

### Reason

Our 4th most searched token.

**Comment by alfetopito** [comment]
Token already in the list
