### ISSUE TITLE
[AddImage] `BZZ` on `MAINNET`

### ISSUE THREAD

**Issue by tonytony32** [cowprotocol/token-lists#147]
### Network

MAINNET

### Address

0x19062190B1925b5b6689D7073fDfC8c2976EF8Cb

### Image URL

https://github.com/tonytony32/swarm/blob/6b9a3d5a5dc7cb749b5a7131f0d00c98ee11c6e7/Circle_Orange_onWhite.png

**Comment by tonytony32** [comment]
Circled image so that it looks better

**Comment by alfetopito** [comment]
> Circled image so that it looks better

Awesome, thanks for the submission!

Just need to link to the raw image directly -> https://raw.githubusercontent.com/tonytony32/swarm/6b9a3d5a5dc7cb749b5a7131f0d00c98ee11c6e7/Circle_Orange_onWhite.png
