### ISSUE TITLE
RPL token logo is incorrect

### ISSUE THREAD

**Issue by maverickrp** [cowprotocol/token-lists#182]
The current logo for RPL is incorrectly showing the rETH logo - please replace it with this instead, thanks! https://github.com/MetaMask/contract-metadata/blob/master/images/rpl.svg

**Comment by alfetopito** [comment]
Hi there!
Thank you for reaching out.

Please use [this form to add/update](https://github.com/cowprotocol/token-lists/issues/new?assignees=&labels=addImage&template=addImageForm.yml&title=%5BAddImage%5D+%60SYMBOL%60+on+%60NETWORK%60) token images
