### ISSUE TITLE
[AddImage] `RPL` on `MAINNET`

### ISSUE THREAD

**Issue by maverickrp** [cowprotocol/token-lists#187]
### Network

MAINNET

### Address

0xd33526068d116ce69f19a9ee46f0bd304f21a51f

### Image URL

https://github.com/MetaMask/contract-metadata/blob/master/images/rpl.svg

**Comment by alfetopito** [comment]
@maverickrp Almost there!

The script needs the direct link to the image. 
In your case, you should use https://raw.githubusercontent.com/MetaMask/contract-metadata/master/images/rpl.svg instead
