### ISSUE TITLE
[AddToken] `SYMBOL` on `NETWORK`

### ISSUE THREAD

**Issue by des0lation** [cowprotocol/token-lists#208]
### Network

MAINNET

### Token Symbol

swETH

### Token Name

Swell Ethereum

### Decimals

18

### Address

0xf951E335afb289353dc249e82926178EaC7DEd78

### Image URL

https://ibb.co/YRGv45v

### Reason

Hey!

Swell is an LST which is sitting just under 37 million in TVL. We entered the space roughly a month ago and are looking to help diversify the current offering of LSTs. We have roughly 19-20 Million of Liquidity across Balancer, Maverick and Univ3 so that shouldn't be an issue. We are really interested in what Cowswap is doing from a meta-aggregator perspective and getting on the token list would help use better recommend Cowswap to our users.

**Comment by alfetopito** [comment]
Hello @des0lation , thank you for your submission.

Unfortunately, our script cannot handle links to pages that host images. In your case for example, using instead the direct link to the image https://i.ibb.co/Vj8X0FX/sw-ETH-Logo-PNG-1.png should work.

**Comment by des0lation** [comment]
Ty I will resubmit
