### ISSUE TITLE
OETH token is showing as both active and unsupported

### ISSUE THREAD

**Issue by sumpg41** [cowprotocol/token-lists#217]
Your request is ready and will be reviewed by a team member.
You can follow the progress in the Pull Request #201

_Originally posted by @github-actions[bot] in https://github.com/cowprotocol/token-lists/issues/200#issuecomment-1563212147_
            
![Screenshot 2023-06-23 at 10 58 07 AM](https://user-images.githubusercontent.com/80375331/248304039-f92a3c19-0342-466d-aa4d-4122907971c1.png)

when searching OETH, it shows as both active and unsupported on CowSwap

**Comment by sumpg41** [comment]
![Screenshot 2023-06-23 at 11 09 44 AM](https://github.com/cowprotocol/token-lists/assets/80375331/17c7de1a-370a-4d38-b0ea-4d99aebb7a93)


trying again populates the token logos but with the same issue

**Comment by elena-zh** [comment]
Dear @sumpg41  ,
Let me try explaining you the difference in 'Unsupported' and 'Active' labels. 
Unsupported means that the token is not yet supported by the CoW Protocol
![image](https://github.com/cowprotocol/token-lists/assets/70885163/3197313c-6853-401f-941e-f497f22c567b)
![image](https://github.com/cowprotocol/token-lists/assets/70885163/f7ecc82e-68b4-48e2-87db-b4ffa4949dd6)

'Active' means that a token is imported, and presents in you current custom tokens list
![imported](https://github.com/cowprotocol/token-lists/assets/70885163/f9c8eadf-6861-4330-909c-6e618a51a6cd)
If you remove it from the custom token list, you will not  see that it is 'Active' while searching for it. 

As for the missing icon, I can't reproduce the issue rn: 
![image](https://github.com/cowprotocol/token-lists/assets/70885163/1efa9aca-cf6e-4219-a4b6-f65a6ef5f808)

**Comment by sumpg41** [comment]
Thanks @elena-zh, shouldn't OETH now be supported though from https://github.com/cowprotocol/token-lists/commit/17706ae184b01b29638b99795c131d0de7ec1c16

**Comment by elena-zh** [comment]
> Thanks @elena-zh, shouldn't OETH now be supported though from [17706ae](https://github.com/cowprotocol/token-lists/commit/17706ae184b01b29638b99795c131d0de7ec1c16)

Adding to a list and a token support are 2 different things.
The token-lists repo controls what’s displayed in the website from the default tokens list.
The actual support is based on backend rules.

I checked with the backed, the token can't be supported by the protocol as it takes fee on transfer. Sorry about that.

**Comment by sumpg41** [comment]
> the token can't be supported by the protocol as it takes fee on transfer

@elena-zh that is not how it works, it does not take any fees on normal transfers or swaps. 

It takes a small fee **if and only if** users exit through the [OETH vault](https://docs.oeth.com/how-it-works)

**Comment by elena-zh** [comment]
@sumpg41 , we will see what we can do for you. I will let you know.

**Comment by alfetopito** [comment]
Hey @sumpg41 , the token has been enabled, you should be able to trade it now.
Let me know if you still see any issues.
