### ISSUE TITLE
OETH token is showing as unsupported

### ISSUE THREAD

**Issue by sumpg41** [cowprotocol/token-lists#220]
Hey @sumpg41 , the token has been enabled, you should be able to trade it now.
Let me know if you still see any issues.

_Originally posted by @alfetopito in https://github.com/cowprotocol/token-lists/issues/217#issuecomment-1618285936_
            
Hey @alfetopito, I am still seeing the OETH token shown as unsupported.

<img width="597" alt="Screenshot 2023-07-05 at 8 47 11 AM" src="https://user-images.githubusercontent.com/80375331/251154038-c30ea77a-bb63-4ca8-b448-5feb7d1f929b.png">

**Comment by elena-zh** [comment]
Hey @sumpg41 , it is tradeable. 
Please clear out your local storage and refresh the browser. 
![image](https://github.com/cowprotocol/token-lists/assets/70885163/eac72ec5-3222-4cf1-81c5-9b85a966c8ab)

**Comment by sumpg41** [comment]
@elena-zh Ah, it is working now, thank you! Could you please also [add this one](https://github.com/cowprotocol/token-lists/pull/224)? It's the same codebase as OETH.

cc @alfetopito

**Comment by alfetopito** [comment]
Thanks for the request!
I'll bring this up internally
