### ISSUE TITLE
OUSD still showing as unsupported 

### ISSUE THREAD

**Issue by sumpg41** [cowprotocol/token-lists#227]
Your request is ready and will be reviewed by a team member.
You can follow the progress in the Pull Request #224

_Originally posted by @github-actions[bot] in https://github.com/cowprotocol/token-lists/issues/223#issuecomment-1624411038_

Hello, it appears that OUSD was added to CowSwap, but the token is still showing as unsupported:

![Screenshot 2023-07-17 at 9 40 56 AM](https://user-images.githubusercontent.com/80375331/254009583-cf83e1f5-d638-4c31-8bde-91557be6a095.png)

OUSD is the same codebase as [OETH](https://github.com/cowprotocol/token-lists/issues/220), so it should appear as tradable. 

@alfetopito @elena-zh could you please enable this token for trading?

**Comment by elena-zh** [comment]
Hey @sumpg41, I reached out to the BE team.

**Comment by sumpg41** [comment]
> Hey @sumpg41, I reached out to the BE team on this. The token should become tradeable next week.

@elena-zh great, thank you

**Comment by elena-zh** [comment]
Hey @sumpg41 , 
the token should be supported now 
![image](https://github.com/cowprotocol/token-lists/assets/70885163/3af6f5ed-3bae-44b1-b925-09ffab977903)
