### ISSUE TITLE
Cow Swap not routing swaps through Curve Pool

### ISSUE THREAD

**Issue by sumpg41** [cowprotocol/token-lists#243]
Hello,

At the moment, it appears that swaps from [ETH to OETH](https://swap.cow.fi/#/1/swap/WETH/OETH) are not being routed thru Curve, they are being routed through other DEXs (likely Uniswap and/or Sushiswap). This is causing significant slippage:

![Screenshot 2023-08-03 at 11 04 05 AM](https://github.com/cowprotocol/token-lists/assets/80375331/26d9e556-3699-41c2-94e9-f980c752ec10)

The OETH Curve Pool is holding a significantly larger amount of liquidity, can we please update the dapp to route through Curve when it makes sense for larger trades? Here is a screenshot of the [Curve pool](https://curve.fi/#/ethereum/pools/factory-v2-298/deposit):

![Screenshot 2023-08-03 at 11 05 09 AM](https://github.com/cowprotocol/token-lists/assets/80375331/80cf4c5d-f1fb-45bd-898b-c2b782e54079)

Thank you!

**Comment by sumpg41** [comment]
It would begreat if the same can be done for swaps from 3CRV stablecoin into OUSD via the [OUSD Curve Pool](https://curve.fi/#/ethereum/pools/factory-v2-9/deposit)

**Comment by alfetopito** [comment]
Short update: I'm checking with the team internally, still waiting on their answer

**Comment by alfetopito** [comment]
As you may or may not be aware, CoW Protocol uses solvers to find the solutions/best execution path.
There's a solver that recently added support for this execution path, so, that route can be used!
The caveat is that, this solver does not yet provides price estimation.
Which means the calculated UI prices/slippage/price impact will not reflect the usage of this pool.

The support for this depends on the solvers, and while they are gradually implementing this feature, there's no clear timeline for when it'll be available.

Summarizing: the pool is supported during execution, but not during price estimation.

I'll then close this issue.
Feel free to re-open if you need more info.

**Comment by sumpg41** [comment]
> The caveat is that, this solver does not yet provides price estimation.
Which means the calculated UI prices/slippage/price impact will not reflect the usage of this pool.

> The support for this depends on the solvers, and while they are gradually implementing this feature, there's no clear timeline for when it'll be available.

> Summarizing: the pool is supported during execution, but not during price estimation.

Can you route through Paraswap? They are able to properly route through Curve:

![Screenshot 2023-08-08 at 9 27 38 AM](https://github.com/cowprotocol/token-lists/assets/80375331/f8de7af9-bf8e-4ec6-b3ef-9cb44056d5d1)

Kyberswap was having a similar issue but was able to make this switch to Paraswap, and is now routing properly

**Comment by alfetopito** [comment]
We do have solvers that route through Paraswap, so - same as the solver I mentioned - the order can be executed via this route.
I'm not sure our price estimators do, though. I'll check.

**Comment by alfetopito** [comment]
Sorry, forgot to update the issue.
Last I checked, we were rate limiting issues with Paraswap API, and the team was working on ways to bring it back online.
I've pinged them again to understand what's the current state.

**Comment by alfetopito** [comment]
Paraswap price estimator has been enabled again!
And the liquidity now is as expected
![image](https://github.com/cowprotocol/token-lists/assets/43217/b21716a7-5d54-4380-b849-d81efbf50301)

Let's us know if you have any further questions.
Closing it for now
