### ISSUE TITLE
[AddToken] `EURe` on `GNOSIS CHAIN`

### ISSUE THREAD

**Issue by mrtdlgc** [cowprotocol/token-lists#245]
### Network

GNOSIS_CHAIN

### Token Symbol

EURe

### Token Name

Monerium EUR emoney

### Decimals

18

### Address

0xcb444e90d8198415266c6a2724b7900fb12fc56e

### Image URL

https://monerium.com/tokens/eur.png

### Reason

The euro e-money token by Monerium EMI, a regulated entity, licensed in the EEA. E-money is recognised as a digital alternative to cash, 1:1 backed in high-quality liquid assets and is unconditionally redeemable on demand.

Plus, it is used for Gnosis Pay Card payments.

**Comment by alfetopito** [comment]
Hi @mrtdlgc , thank you for your contribution.

EURe is already on the list https://files.cow.fi/tokens/CowSwap.json
