### ISSUE TITLE
[AddToken] `lp-yCRVv2` on `MAINNET`

### ISSUE THREAD

**Issue by MarcoWorms** [cowprotocol/token-lists#339]
### Network

MAINNET

### Token Symbol

lp-yCRVv2

### Token Name

lp-yCRV v2

### Decimals

18

### Address

0x6E9455D109202b426169F0d8f01A3332DAE160f3

### Image URL

https://i.imgur.com/CD0MZ72.png

### Reason

this is the Yearn lp-yCRV token, which address can be confirmed in docs: https://docs.yearn.fi/getting-started/products/ylockers/ycrv/overview

**Comment by MarcoWorms** [comment]
hey i renamed this token maybe retriger the bot that creates the PR?

**Comment by alfetopito** [comment]
Hey @MarcoWorms, I've adjusted the name and symbol to match the contract
