### ISSUE TITLE
[AddToken] `CAKE` on `ARB`

### ISSUE THREAD

**Issue by chefmaroon** [cowprotocol/token-lists#413]
### Network

ARBITRUM_ONE

### Token Symbol

CAKE

### Token Name

PancakeSwap Token

### Decimals

18

### Address

0x1b896893dfc86bb67Cf57767298b9073D2c1bA2c

### Image URL

https://images2.imgbox.com/06/90/oFIjbJwJ_o.png

### Reason

1) 20k holders on Arbitrum
2) $85k liquidity on ARB PCS
3) ARB PCS has 9k DAU

**Comment by cmagan** [comment]
I'd support this request
