### ISSUE TITLE
[AddImage] `GHO` on `MAINNET`

### ISSUE THREAD

**Issue by trallas** [cowprotocol/token-lists#475]
### Network

MAINNET

### Address

0x40D16FC0246aD3160Ccc09B8D0D3A2cD28aE6C2f

### Image URL

curl -o img.png <https://github.com/aave/gho-brand-assets/blob/main/Logo/PNG/GHO_logo_full_green.png>

**Comment by alfetopito** [comment]
Hey @trallas , thanks for the contribution!

One tip, use the RAW github URL instead.
In this case it would be: https://raw.githubusercontent.com/aave/gho-brand-assets/main/Logo/PNG/GHO_logo_full_green.png

Also, only the URL.
The `curl` command was an example of how to verify you are using the image the script expects.

Also, do you really mean to use the token name for the logo?

**Comment by trallas** [comment]
Hi leandro
Thanks, got it. Lets see if I did it correctly this time. Thanks!
