### ISSUE TITLE
VOLT on ETHEREUM

### ISSUE THREAD

**Issue by richland100** [cowprotocol/token-lists#524]
Can you please add VOLT to the approved token list.  Been in the top 8 ranking on Dexscreener for 2 weeks.  #1 today

**Comment by alfetopito** [comment]
Hello @richland100.
Thank you for your interest in CoW Protocol!

First of all, which VOLT are you referring to? 
Second, please use this form for suggesting tokens https://github.com/cowprotocol/token-lists/issues/new?assignees=&labels=addToken&projects=&template=1-addTokenForm.yml&title=%5BAddToken%5D+%60SYMBOL%60+on+%60NETWORK%60

Keep in mind filling the form doesn't guarantee it'll be added to the default token list.
