### ISSUE TITLE
[AddToken] `SYMBOL` on `NETWORK`

### ISSUE THREAD

**Issue by Gus5000** [cowprotocol/token-lists#697]
### Network

MAINNET

### Token Symbol

FI

### Token Name

Fideum

### Decimals

18

### Address

0x1294f4183763743c7c9519Bec51773fb3aCD78FD

### Image URL

https://www.fideum.com/

### Reason

Supported until today,   please reinstate support

**Comment by alfetopito** [comment]
Hey @Gus5000 , there was a bug on the image processing workflow. I just fixed it, should work now.

**Comment by Gus5000** [comment]
Still,    Unsupported,    is there a time thing for it?     Thanks





￼
